### ISSUE TITLE
Crop images with circle shape

### ISSUE THREAD

**Issue by kiaxseventh** [godaangel/flutter_crop_box#2]
hello dear @godaangel 
does it support Crop images with circle shape ?

**Comment by godaangel** [comment]
> hello dear @godaangel
> does it support Crop images with circle shape ?

hello，thx for this issue，now it dose not support circle shape，I will do it recently

**Comment by godaangel** [comment]
> hello dear @godaangel
> does it support Crop images with circle shape ?

**Comment by kiaxseventh** [comment]
thanks for you answer

can you say when time can you do it ?
I look forward to this feature

**Comment by godaangel** [comment]
> thanks for you answer
> 
> can you say when time can you do it ?
> I look forward to this feature

can you give me more details for this feature? I want to know what does this feature look like. I mean the return params is `CenterPoint<x, y>` and `Radius<doule>`   or like now params `Rect(top, right, bottom, left)`?

**Comment by godaangel** [comment]
and I think maybe `Rect(top, right, bottom, left)` is enough, because I can trans now crop square to circle in view, and also return 
`Rect(top, right, bottom, left)` and you can use this return to crop real image to square, and in your Interface you can use `ClipRect` widget to do circle. 

this will be fast

**Comment by kiaxseventh** [comment]
just i need a circle ui for crop image
and end output image file a 1:1 Square image

just when crop image show Circle UI

**Comment by godaangel** [comment]
> just i need a circle ui for crop image
> and end output image file a 1:1 Square image
> 
> just when crop image show Circle UI

ok, I will finish it tonight, now time is 17:24

**Comment by godaangel** [comment]
> just i need a circle ui for crop image
> and end output image file a 1:1 Square image
> 
> just when crop image show Circle UI

I have finish this issue，you can use `cropBoxType: CropBoxType.Circle` to set UI to Circle
