### ISSUE TITLE
How to get the Initial CropRect.

### ISSUE THREAD

**Issue by shamnex** [godaangel/flutter_crop_box#4]
Thank you for a very useful plugin. Been extremely useful on a project I'm working on. 

I wanted ask if it's possible to have a callback with the cropRect on Instantiation. Currently I'm only able to get the cropRect only when you interact with with the CropBox. 

This could be really useful when you want to crop an image with the default CropBox settings without any user interaction. Let me know if it's something that is possible.

Thank you.

**Comment by godaangel** [comment]
@shamnex thank you for your question，
I think you mean you want to get cropRect when it's initial. so you can use cropRectUpdate this callback, it will run when cropbox initial. it's my fault that I haven't say it in document

**Comment by shamnex** [comment]
Alright man.  Thanks!
