### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by ghost** [godaangel/flutter_crop_box#5]
Hello,
could you please update your dependencies? I cannot update it since it would be incompatible with Easy Localizations..

Because crop_box >=0.1.9 depends on exif 1.0.3 which depends on args ^1.2.0, crop_box >=0.1.9 requires args ^1.2.0.
And because easy_localization >=3.0.0-nullsafety depends on args ^2.0.0, crop_box >=0.1.9 is incompatible with easy_localization >=3.0.0-nullsafety.
So, because kukia depends on both easy_localization ^3.0.0-nullsafety and crop_box ^0.1.13, version solving failed.
pub get failed (1; So, because kukia depends on both easy_localization ^3.0.0-nullsafety and crop_box ^0.1.13, version solving failed.)

Thank you :)

**Comment by godaangel** [comment]
> Hello,
> could you please update your dependencies? I cannot update it since it would be incompatible with Easy Localizations..
> 
> Because crop_box >=0.1.9 depends on exif 1.0.3 which depends on args ^1.2.0, crop_box >=0.1.9 requires args ^1.2.0.
> And because easy_localization >=3.0.0-nullsafety depends on args ^2.0.0, crop_box >=0.1.9 is incompatible with easy_localization >=3.0.0-nullsafety.
> So, because kukia depends on both easy_localization ^3.0.0-nullsafety and crop_box ^0.1.13, version solving failed.
> pub get failed (1; So, because kukia depends on both easy_localization ^3.0.0-nullsafety and crop_box ^0.1.13, version solving failed.)
> 
> Thank you :)

ok，I will do this nullsafety

**Comment by godaangel** [comment]
@Kimonnn 
hello, I have add null-safety and update dependencies, you can try version `1.0.1`
