### ISSUE TITLE
Preview Crop?

### ISSUE THREAD

**Issue by shamnex** [godaangel/flutter_crop_box#6]
Hi again.

Is it possible preview the crop area (without the grid, without the cropped our area) and show a sample  of what the speculative cropped result would look like without actually cropping it ?  This means just showing current Crop Area and nothing else . 

Thanks

**Comment by godaangel** [comment]
ok。I will give some configs

**Comment by godaangel** [comment]
I had review my code，i have found that you can use `example` code, in `example` there has a demo form crop preview， image data is `Uint8List`， only in memory, not in file，that can be used to your issue

**Comment by shamnex** [comment]
Hello, thanks again for all the effort. What I was asking isn't actually cropping image but just a way just to show only the crop area regardless of it's an image or video.

**Comment by godaangel** [comment]
> Hello, thanks again for all the effort. What I was asking isn't actually cropping image but just a way just to show only the crop area regardless of it's an image or video.

ok, I will finish it today

**Comment by godaangel** [comment]
I have add a `maskColor` to resolve this, you can try it @shamnex

**Comment by shamnex** [comment]
Thank you so much for this.

**Comment by godaangel** [comment]
:)
